/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.invoker;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ApiV2AttachmentsPostRequest.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AttachmentChangeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AttachmentChangeViewModelArrayWorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AttachmentModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AttachmentModelAutoTestStepResultsModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AttachmentPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AttachmentPutModelAutoTestStepResultsModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AttachmentSubGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestAverageDurationModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestChangeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestChangeViewModelArrayWorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestIdModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestModelV2GetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestNamespaceModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestResultsForTestRunModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutoTestStepModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutotestFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutotestHistoricalResultSelectModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutotestResultHistoricalGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutotestResultReasonSubGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutotestSelectModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutotestsExtractionModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.AutotestsSelectModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.BackgroundJobAttachmentModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.BackgroundJobModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.BooleanNullableTestPlanChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.BooleanTestPlanChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.BooleanWorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ConfigurationByParametersModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ConfigurationModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ConfigurationPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ConfigurationPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ConfigurationSelectModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeChangeModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeOptionModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeOptionPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributePostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributePutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeSearchQueryModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeTemplateModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeTemplatePostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeTemplatePutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeTemplateSearchQueryModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.CustomAttributeTestPlanProjectRelationPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.DateTimeRangeSelectorModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ExternalLinkModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.FailureClassModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.FailureClassRegexModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.FilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.FlakyBulkModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.GetXlsxTestPointsByTestPlanModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.GlobalCustomAttributePostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.GlobalCustomAttributeUpdateModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.GuidExtractionModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.GuidWorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.Int32RangeSelectorModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.Int32WorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.Int64RangeSelectorModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.Int64WorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.IterationModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.IterationPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.LabelPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.LabelShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.LastTestResultModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.LinkModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.LinkPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.LinkPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.LinkSubGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.NoContentResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.NotificationModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.NotificationQueryFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.Operation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ParameterFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ParameterGroupModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ParameterIterationModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ParameterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ParameterPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ParameterPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ParameterShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.PeriodViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.PeriodViewModelTestPlanChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProblemDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectAttributesFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectCustomAttributeTemplateGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectCustomAttributesTemplatesFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectExportQueryModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectExportWithTestPlansPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectShortestModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectTestPlansFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ProjectsFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.PublicTestPointModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.PublicTestRunModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SearchAutoTestsQueryIncludesModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SearchCustomAttributeTemplateGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SearchWebhooksQueryModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SectionModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SectionMoveModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SectionPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SectionPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SectionRenameModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SectionWithStepsModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SharedStepChangeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SharedStepModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SharedStepReferenceModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SharedStepReferenceSectionModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SharedStepReferenceSectionsQueryFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SharedStepReferencesQueryFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.SharedStepResultModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ShortConfiguration.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.StepCommentModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.StepModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.StepPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.StepResultModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.StringArrayTestPlanChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.StringArrayWorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.StringTestPlanChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.StringWorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TagShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanChangeModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanChangedFieldsViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanGroupByStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanGroupByTestSuite.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanGroupByTester.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanGroupByTesterAndStatus.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanLink.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanWithAnalyticModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPlanWithTestSuiteTreeModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointAnalyticResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointByTestSuiteModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointChangeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointChangeViewModelTestPlanChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointResultModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointSelectModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointSelector.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointShortGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointWithLastResultModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestPointsExtractionModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultChangeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultChangeViewModelTestPlanChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultChronologyModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultHistoryReportModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultShortGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultStepCommentPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultUpdateModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultV2GetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultV2ShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultsFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultsLocalFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestResultsStatisticsGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunAnalyticResultModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunFillByAutoTestsPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunFillByConfigurationsPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunFillByWorkItemsPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunGroupByFailureClassModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunGroupByStatusModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunSearchQueryModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunShortGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunStatisticsErrorCategoriesGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunStatisticsStatusesGetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunTestResultsPartialBulkSetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunTestResultsSelectModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunV2GetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunV2PostShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestRunV2PutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestSuiteChangeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestSuiteChangeViewModelTestPlanChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestSuiteV2GetModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestSuiteV2PostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestSuiteV2PutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestSuiteV2TreeModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestSuiteWithChildrenModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.TestSuiteWorkItemsSearchModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.UserRankModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.UserWithRankModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ValidateAntiForgeryTokenAttribute.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.ValidationProblemDetails.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WebHookLogModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WebHookModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WebHookPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemChangeModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemChangedAttributeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemChangedFieldsViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemCommentModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemCommentPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemCommentPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemFilterModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemIdModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemIdentifierModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemLikeModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemLinkChangeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemMovePostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemPostModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemPutModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemSearchQueryModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemSelectModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemShortModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemStepChangeViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemStepChangeViewModelArrayWorkItemChangedFieldViewModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemVersionModel.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new io.test_gear.client.model.WorkItemsExtractionModel.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
