/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.api;

import io.test_gear.client.invoker.*;

import org.junit.jupiter.api.Test;

/**
 * API tests for AttachmentsApi
 */
public class AttachmentsApiTest {

    private final AttachmentsApi api = new AttachmentsApi();

    /**
     * Delete attachment file
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2AttachmentsIdDeleteTest() throws ApiException {
        //UUID id = null;
        //api.apiV2AttachmentsIdDelete(id);
        // TODO: test validations
    }

    /**
     * Download attachment file
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2AttachmentsIdGetTest() throws ApiException {
        //UUID id = null;
        //Integer width = null;
        //Integer height = null;
        //ImageResizeType resizeType = null;
        //String backgroundColor = null;
        //Boolean preview = null;
        //File response = api.apiV2AttachmentsIdGet(id, width, height, resizeType, backgroundColor, preview);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2AttachmentsOccupiedFileStorageSizeGetTest() throws ApiException {
        //Float response = api.apiV2AttachmentsOccupiedFileStorageSizeGet();
        // TODO: test validations
    }

    /**
     * Upload new attachment file
     *
     * File size is restricted to 1 GB (1 073 741 824 bytes)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2AttachmentsPostTest() throws ApiException {
        //File _file = null;
        //AttachmentModel response = api.apiV2AttachmentsPost(_file);
        // TODO: test validations
    }

}
