/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.api;

import io.test_gear.client.invoker.*;

import org.junit.jupiter.api.Test;

/**
 * API tests for CustomAttributesApi
 */
public class CustomAttributesApiTest {

    private final CustomAttributesApi api = new CustomAttributesApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesIdDeleteTest() throws ApiException {
        //UUID id = null;
        //api.apiV2CustomAttributesIdDelete(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesIdGetTest() throws ApiException {
        //UUID id = null;
        //CustomAttributeModel response = api.apiV2CustomAttributesIdGet(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesIdMakeGlobalPostTest() throws ApiException {
        //UUID id = null;
        //api.apiV2CustomAttributesIdMakeGlobalPost(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesIdProjectsGetTest() throws ApiException {
        //UUID id = null;
        //List<ProjectShortestModel> response = api.apiV2CustomAttributesIdProjectsGet(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesIdPutTest() throws ApiException {
        //UUID id = null;
        //CustomAttributeUpdateModel customAttributeUpdateModel = null;
        //api.apiV2CustomAttributesIdPut(id, customAttributeUpdateModel);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesMergePostTest() throws ApiException {
        //CustomAttributeMergeToGlobalModel customAttributeMergeToGlobalModel = null;
        //CustomAttributeModel response = api.apiV2CustomAttributesMergePost(customAttributeMergeToGlobalModel);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesOrderPostTest() throws ApiException {
        //CustomAttributeSetPositionsModel customAttributeSetPositionsModel = null;
        //api.apiV2CustomAttributesOrderPost(customAttributeSetPositionsModel);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesPostTest() throws ApiException {
        //CustomAttributePostModel customAttributePostModel = null;
        //CustomAttributeModel response = api.apiV2CustomAttributesPost(customAttributePostModel);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesReplacePostTest() throws ApiException {
        //CustomAttributeReplaceModel customAttributeReplaceModel = null;
        //CustomAttributeModel response = api.apiV2CustomAttributesReplacePost(customAttributeReplaceModel);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2CustomAttributesSearchPostTest() throws ApiException {
        //Integer skip = null;
        //Integer take = null;
        //String orderBy = null;
        //String searchField = null;
        //String searchValue = null;
        //CustomAttributeSearchQueryModel customAttributeSearchQueryModel = null;
        //List<CustomAttributeModel> response = api.apiV2CustomAttributesSearchPost(skip, take, orderBy, searchField, searchValue, customAttributeSearchQueryModel);
        // TODO: test validations
    }

}
