/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.api;

import io.test_gear.client.invoker.*;

import org.junit.jupiter.api.Test;

/**
 * API tests for TagsApi
 */
public class TagsApiTest {

    private final TagsApi api = new TagsApi();

    /**
     * Get all Tags
     *
     * &lt;br&gt;Use case  &lt;br&gt;User runs method execution  &lt;br&gt;System returns tags (listed in the response example)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2TagsGetTest() throws ApiException {
        //api.apiV2TagsGet();
        // TODO: test validations
    }

    /**
     * Get all Tags that are used in TestPlans
     *
     * &lt;br&gt;Use case  &lt;br&gt;User runs method execution  &lt;br&gt;System returns tags (listed in the response example)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2TagsTestPlansTagsGetTest() throws ApiException {
        //Integer skip = null;
        //Integer take = null;
        //String orderBy = null;
        //String searchField = null;
        //String searchValue = null;
        //List<TagShortModel> response = api.apiV2TagsTestPlansTagsGet(skip, take, orderBy, searchField, searchValue);
        // TODO: test validations
    }

}
