/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.api;

import io.test_gear.client.invoker.*;

import org.junit.jupiter.api.Test;

/**
 * API tests for TestPointsApi
 */
public class TestPointsApiTest {

    private final TestPointsApi api = new TestPointsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2TestPointsIdTestRunsGetTest() throws ApiException {
        //UUID id = null;
        //List<TestRunModel> response = api.apiV2TestPointsIdTestRunsGet(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2TestPointsIdWorkItemGetTest() throws ApiException {
        //UUID id = null;
        //WorkItemModel response = api.apiV2TestPointsIdWorkItemGet(id);
        // TODO: test validations
    }

}
