/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.api;

import io.test_gear.client.invoker.*;

import org.junit.jupiter.api.Test;

/**
 * API tests for WebhooksLogsApi
 */
public class WebhooksLogsApiTest {

    private final WebhooksLogsApi api = new WebhooksLogsApi();

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2WebhooksLogsGetTest() throws ApiException {
        //UUID projectId = null;
        //Integer skip = null;
        //Integer take = null;
        //String orderBy = null;
        //String searchField = null;
        //String searchValue = null;
        //List<WebHookLogModel> response = api.apiV2WebhooksLogsGet(projectId, skip, take, orderBy, searchField, searchValue);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2WebhooksLogsIdDeleteTest() throws ApiException {
        //UUID id = null;
        //api.apiV2WebhooksLogsIdDelete(id);
        // TODO: test validations
    }

    /**
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2WebhooksLogsIdGetTest() throws ApiException {
        //UUID id = null;
        //WebHookLogModel response = api.apiV2WebhooksLogsIdGet(id);
        // TODO: test validations
    }

}
