/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.api;

import io.test_gear.client.invoker.*;

import org.junit.jupiter.api.Test;

/**
 * API tests for WorkItemsCommentsApi
 */
public class WorkItemsCommentsApiTest {

    private final WorkItemsCommentsApi api = new WorkItemsCommentsApi();

    /**
     * Delete WorkItem comment
     *
     * &lt;br&gt;Use case  &lt;br&gt;User sets comment identifier  &lt;br&gt;User runs method execution  &lt;br&gt;System delete comment   &lt;br&gt;System returns success status code
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2WorkItemsCommentsCommentIdDeleteTest() throws ApiException {
        //UUID commentId = null;
        //api.apiV2WorkItemsCommentsCommentIdDelete(commentId);
        // TODO: test validations
    }

    /**
     * Create WorkItem comment
     *
     * &lt;br&gt;Use case  &lt;br&gt;User sets comment properties (listed in request parameters)  &lt;br&gt;User runs method execution  &lt;br&gt;System creates comment   &lt;br&gt;System returns comment model (listed in response parameters)
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2WorkItemsCommentsPostTest() throws ApiException {
        //WorkItemCommentPostModel workItemCommentPostModel = null;
        //WorkItemCommentModel response = api.apiV2WorkItemsCommentsPost(workItemCommentPostModel);
        // TODO: test validations
    }

    /**
     * Update WorkItem comment
     *
     * &lt;br&gt;Use case  &lt;br&gt;User sets comment properties (listed in request parameters)  &lt;br&gt;User runs method execution  &lt;br&gt;System updates comment   &lt;br&gt;System returns success status code
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2WorkItemsCommentsPutTest() throws ApiException {
        //WorkItemCommentPutModel workItemCommentPutModel = null;
        //api.apiV2WorkItemsCommentsPut(workItemCommentPutModel);
        // TODO: test validations
    }

    /**
     * Get WorkItem comments by Id or GlobalId
     *
     * &lt;br&gt;Use case  &lt;br&gt;User sets workitem identifier  &lt;br&gt;User runs method execution  &lt;br&gt;System search comments by workitem identifier  &lt;br&gt;System returns comments 
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void apiV2WorkItemsIdCommentsGetTest() throws ApiException {
        //String id = null;
        //List<WorkItemCommentModel> response = api.apiV2WorkItemsIdCommentsGet(id);
        // TODO: test validations
    }

}
