/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for AutoTestPostModel
 */
public class AutoTestPostModelTest {
    private final AutoTestPostModel model = new AutoTestPostModel();

    /**
     * Model tests for AutoTestPostModel
     */
    @Test
    public void testAutoTestPostModel() {
        // TODO: test AutoTestPostModel
    }

    /**
     * Test the property 'workItemIdsForLinkWithAutoTest'
     */
    @Test
    public void workItemIdsForLinkWithAutoTestTest() {
        // TODO: test workItemIdsForLinkWithAutoTest
    }

    /**
     * Test the property 'shouldCreateWorkItem'
     */
    @Test
    public void shouldCreateWorkItemTest() {
        // TODO: test shouldCreateWorkItem
    }

    /**
     * Test the property 'externalId'
     */
    @Test
    public void externalIdTest() {
        // TODO: test externalId
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'namespace'
     */
    @Test
    public void namespaceTest() {
        // TODO: test namespace
    }

    /**
     * Test the property 'classname'
     */
    @Test
    public void classnameTest() {
        // TODO: test classname
    }

    /**
     * Test the property 'steps'
     */
    @Test
    public void stepsTest() {
        // TODO: test steps
    }

    /**
     * Test the property 'setup'
     */
    @Test
    public void setupTest() {
        // TODO: test setup
    }

    /**
     * Test the property 'teardown'
     */
    @Test
    public void teardownTest() {
        // TODO: test teardown
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'isFlaky'
     */
    @Test
    public void isFlakyTest() {
        // TODO: test isFlaky
    }

}
