/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomAttributeTemplateSearchResponseModel
 */
public class CustomAttributeTemplateSearchResponseModelTest {
    private final CustomAttributeTemplateSearchResponseModel model = new CustomAttributeTemplateSearchResponseModel();

    /**
     * Model tests for CustomAttributeTemplateSearchResponseModel
     */
    @Test
    public void testCustomAttributeTemplateSearchResponseModel() {
        // TODO: test CustomAttributeTemplateSearchResponseModel
    }

    /**
     * Test the property 'projectShortestModels'
     */
    @Test
    public void projectShortestModelsTest() {
        // TODO: test projectShortestModels
    }

    /**
     * Test the property 'customAttributeModels'
     */
    @Test
    public void customAttributeModelsTest() {
        // TODO: test customAttributeModels
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
