/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomAttributeTemplateSearchQueryModel
 */
public class CustomAttributeTemplateSearchQueryModelTest {
    private final CustomAttributeTemplateSearchQueryModel model = new CustomAttributeTemplateSearchQueryModel();

    /**
     * Model tests for CustomAttributeTemplateSearchQueryModel
     */
    @Test
    public void testCustomAttributeTemplateSearchQueryModel() {
        // TODO: test CustomAttributeTemplateSearchQueryModel
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'projectIds'
     */
    @Test
    public void projectIdsTest() {
        // TODO: test projectIds
    }

    /**
     * Test the property 'customAttributeTypes'
     */
    @Test
    public void customAttributeTypesTest() {
        // TODO: test customAttributeTypes
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

}
