/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for CustomAttributeUpdateModel
 */
public class CustomAttributeUpdateModelTest {
    private final CustomAttributeUpdateModel model = new CustomAttributeUpdateModel();

    /**
     * Model tests for CustomAttributeUpdateModel
     */
    @Test
    public void testCustomAttributeUpdateModel() {
        // TODO: test CustomAttributeUpdateModel
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'options'
     */
    @Test
    public void optionsTest() {
        // TODO: test options
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'required'
     */
    @Test
    public void requiredTest() {
        // TODO: test required
    }

    /**
     * Test the property 'isGlobal'
     */
    @Test
    public void isGlobalTest() {
        // TODO: test isGlobal
    }

}
