/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for IterationPutModel
 */
public class IterationPutModelTest {
    private final IterationPutModel model = new IterationPutModel();

    /**
     * Model tests for IterationPutModel
     */
    @Test
    public void testIterationPutModel() {
        // TODO: test IterationPutModel
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
