/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for LastTestResultModel
 */
public class LastTestResultModelTest {
    private final LastTestResultModel model = new LastTestResultModel();

    /**
     * Model tests for LastTestResultModel
     */
    @Test
    public void testLastTestResultModel() {
        // TODO: test LastTestResultModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'testRunId'
     */
    @Test
    public void testRunIdTest() {
        // TODO: test testRunId
    }

    /**
     * Test the property 'autoTestId'
     */
    @Test
    public void autoTestIdTest() {
        // TODO: test autoTestId
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'workItemVersionId'
     */
    @Test
    public void workItemVersionIdTest() {
        // TODO: test workItemVersionId
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

}
