/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for ProjectModel
 */
public class ProjectModelTest {
    private final ProjectModel model = new ProjectModel();

    /**
     * Model tests for ProjectModel
     */
    @Test
    public void testProjectModel() {
        // TODO: test ProjectModel
    }

    /**
     * Test the property 'attributesScheme'
     */
    @Test
    public void attributesSchemeTest() {
        // TODO: test attributesScheme
    }

    /**
     * Test the property 'testPlansAttributesScheme'
     */
    @Test
    public void testPlansAttributesSchemeTest() {
        // TODO: test testPlansAttributesScheme
    }

    /**
     * Test the property 'testCasesCount'
     */
    @Test
    public void testCasesCountTest() {
        // TODO: test testCasesCount
    }

    /**
     * Test the property 'sharedStepsCount'
     */
    @Test
    public void sharedStepsCountTest() {
        // TODO: test sharedStepsCount
    }

    /**
     * Test the property 'checkListsCount'
     */
    @Test
    public void checkListsCountTest() {
        // TODO: test checkListsCount
    }

    /**
     * Test the property 'autoTestsCount'
     */
    @Test
    public void autoTestsCountTest() {
        // TODO: test autoTestsCount
    }

    /**
     * Test the property 'isFavorite'
     */
    @Test
    public void isFavoriteTest() {
        // TODO: test isFavorite
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'createdById'
     */
    @Test
    public void createdByIdTest() {
        // TODO: test createdById
    }

    /**
     * Test the property 'modifiedById'
     */
    @Test
    public void modifiedByIdTest() {
        // TODO: test modifiedById
    }

    /**
     * Test the property 'globalId'
     */
    @Test
    public void globalIdTest() {
        // TODO: test globalId
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
