/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for PublicTestRunModel
 */
public class PublicTestRunModelTest {
    private final PublicTestRunModel model = new PublicTestRunModel();

    /**
     * Model tests for PublicTestRunModel
     */
    @Test
    public void testPublicTestRunModel() {
        // TODO: test PublicTestRunModel
    }

    /**
     * Test the property 'testRunId'
     */
    @Test
    public void testRunIdTest() {
        // TODO: test testRunId
    }

    /**
     * Test the property 'testPlanId'
     */
    @Test
    public void testPlanIdTest() {
        // TODO: test testPlanId
    }

    /**
     * Test the property 'testPlanGlobalId'
     */
    @Test
    public void testPlanGlobalIdTest() {
        // TODO: test testPlanGlobalId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'build'
     */
    @Test
    public void buildTest() {
        // TODO: test build
    }

    /**
     * Test the property 'configurations'
     */
    @Test
    public void configurationsTest() {
        // TODO: test configurations
    }

    /**
     * Test the property 'autoTests'
     */
    @Test
    public void autoTestsTest() {
        // TODO: test autoTests
    }

    /**
     * Test the property 'testPoints'
     */
    @Test
    public void testPointsTest() {
        // TODO: test testPoints
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

}
