/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for SectionWithStepsModel
 */
public class SectionWithStepsModelTest {
    private final SectionWithStepsModel model = new SectionWithStepsModel();

    /**
     * Model tests for SectionWithStepsModel
     */
    @Test
    public void testSectionWithStepsModel() {
        // TODO: test SectionWithStepsModel
    }

    /**
     * Test the property 'preconditionSteps'
     */
    @Test
    public void preconditionStepsTest() {
        // TODO: test preconditionSteps
    }

    /**
     * Test the property 'postconditionSteps'
     */
    @Test
    public void postconditionStepsTest() {
        // TODO: test postconditionSteps
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'parentId'
     */
    @Test
    public void parentIdTest() {
        // TODO: test parentId
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'createdById'
     */
    @Test
    public void createdByIdTest() {
        // TODO: test createdById
    }

    /**
     * Test the property 'modifiedById'
     */
    @Test
    public void modifiedByIdTest() {
        // TODO: test modifiedById
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
