/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for SharedStepReferenceModel
 */
public class SharedStepReferenceModelTest {
    private final SharedStepReferenceModel model = new SharedStepReferenceModel();

    /**
     * Model tests for SharedStepReferenceModel
     */
    @Test
    public void testSharedStepReferenceModel() {
        // TODO: test SharedStepReferenceModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'globalId'
     */
    @Test
    public void globalIdTest() {
        // TODO: test globalId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'entityTypeName'
     */
    @Test
    public void entityTypeNameTest() {
        // TODO: test entityTypeName
    }

    /**
     * Test the property 'hasThisSharedStepAsStep'
     */
    @Test
    public void hasThisSharedStepAsStepTest() {
        // TODO: test hasThisSharedStepAsStep
    }

    /**
     * Test the property 'hasThisSharedStepAsPrecondition'
     */
    @Test
    public void hasThisSharedStepAsPreconditionTest() {
        // TODO: test hasThisSharedStepAsPrecondition
    }

    /**
     * Test the property 'hasThisSharedStepAsPostcondition'
     */
    @Test
    public void hasThisSharedStepAsPostconditionTest() {
        // TODO: test hasThisSharedStepAsPostcondition
    }

    /**
     * Test the property 'createdById'
     */
    @Test
    public void createdByIdTest() {
        // TODO: test createdById
    }

    /**
     * Test the property 'modifiedById'
     */
    @Test
    public void modifiedByIdTest() {
        // TODO: test modifiedById
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'priority'
     */
    @Test
    public void priorityTest() {
        // TODO: test priority
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

    /**
     * Test the property 'versionId'
     */
    @Test
    public void versionIdTest() {
        // TODO: test versionId
    }

}
