/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for StepResultModel
 */
public class StepResultModelTest {
    private final StepResultModel model = new StepResultModel();

    /**
     * Model tests for StepResultModel
     */
    @Test
    public void testStepResultModel() {
        // TODO: test StepResultModel
    }

    /**
     * Test the property 'stepId'
     */
    @Test
    public void stepIdTest() {
        // TODO: test stepId
    }

    /**
     * Test the property 'outcome'
     */
    @Test
    public void outcomeTest() {
        // TODO: test outcome
    }

    /**
     * Test the property 'sharedStepVersionId'
     */
    @Test
    public void sharedStepVersionIdTest() {
        // TODO: test sharedStepVersionId
    }

    /**
     * Test the property 'sharedStepResults'
     */
    @Test
    public void sharedStepResultsTest() {
        // TODO: test sharedStepResults
    }

}
