/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestResultCreateModel
 */
public class TestResultCreateModelTest {
    private final TestResultCreateModel model = new TestResultCreateModel();

    /**
     * Model tests for TestResultCreateModel
     */
    @Test
    public void testTestResultCreateModel() {
        // TODO: test TestResultCreateModel
    }

    /**
     * Test the property 'durationInMs'
     */
    @Test
    public void durationInMsTest() {
        // TODO: test durationInMs
    }

    /**
     * Test the property 'stepComments'
     */
    @Test
    public void stepCommentsTest() {
        // TODO: test stepComments
    }

    /**
     * Test the property 'failureClassIds'
     */
    @Test
    public void failureClassIdsTest() {
        // TODO: test failureClassIds
    }

    /**
     * Test the property 'outcome'
     */
    @Test
    public void outcomeTest() {
        // TODO: test outcome
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

    /**
     * Test the property 'stepResults'
     */
    @Test
    public void stepResultsTest() {
        // TODO: test stepResults
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

}
