/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestRunAnalyticResultModel
 */
public class TestRunAnalyticResultModelTest {
    private final TestRunAnalyticResultModel model = new TestRunAnalyticResultModel();

    /**
     * Model tests for TestRunAnalyticResultModel
     */
    @Test
    public void testTestRunAnalyticResultModel() {
        // TODO: test TestRunAnalyticResultModel
    }

    /**
     * Test the property 'countGroupByStatus'
     */
    @Test
    public void countGroupByStatusTest() {
        // TODO: test countGroupByStatus
    }

    /**
     * Test the property 'countGroupByFailureClass'
     */
    @Test
    public void countGroupByFailureClassTest() {
        // TODO: test countGroupByFailureClass
    }

}
