/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestPlanSearchQueryModel
 */
public class TestPlanSearchQueryModelTest {
    private final TestPlanSearchQueryModel model = new TestPlanSearchQueryModel();

    /**
     * Model tests for TestPlanSearchQueryModel
     */
    @Test
    public void testTestPlanSearchQueryModel() {
        // TODO: test TestPlanSearchQueryModel
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'build'
     */
    @Test
    public void buildTest() {
        // TODO: test build
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'globalIds'
     */
    @Test
    public void globalIdsTest() {
        // TODO: test globalIds
    }

    /**
     * Test the property 'isLocked'
     */
    @Test
    public void isLockedTest() {
        // TODO: test isLocked
    }

    /**
     * Test the property 'lockedDate'
     */
    @Test
    public void lockedDateTest() {
        // TODO: test lockedDate
    }

    /**
     * Test the property 'automaticDurationTimer'
     */
    @Test
    public void automaticDurationTimerTest() {
        // TODO: test automaticDurationTimer
    }

    /**
     * Test the property 'createdByIds'
     */
    @Test
    public void createdByIdsTest() {
        // TODO: test createdByIds
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'startDate'
     */
    @Test
    public void startDateTest() {
        // TODO: test startDate
    }

    /**
     * Test the property 'endDate'
     */
    @Test
    public void endDateTest() {
        // TODO: test endDate
    }

    /**
     * Test the property 'tagNames'
     */
    @Test
    public void tagNamesTest() {
        // TODO: test tagNames
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

}
