/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestPlanLink
 */
public class TestPlanLinkTest {
    private final TestPlanLink model = new TestPlanLink();

    /**
     * Model tests for TestPlanLink
     */
    @Test
    public void testTestPlanLink() {
        // TODO: test TestPlanLink
    }

    /**
     * Test the property 'bugLink'
     */
    @Test
    public void bugLinkTest() {
        // TODO: test bugLink
    }

    /**
     * Test the property 'workItemGlobalId'
     */
    @Test
    public void workItemGlobalIdTest() {
        // TODO: test workItemGlobalId
    }

    /**
     * Test the property 'workItemName'
     */
    @Test
    public void workItemNameTest() {
        // TODO: test workItemName
    }

    /**
     * Test the property 'configurationName'
     */
    @Test
    public void configurationNameTest() {
        // TODO: test configurationName
    }

    /**
     * Test the property 'createdById'
     */
    @Test
    public void createdByIdTest() {
        // TODO: test createdById
    }

    /**
     * Test the property 'comment'
     */
    @Test
    public void commentTest() {
        // TODO: test comment
    }

    /**
     * Test the property 'info'
     */
    @Test
    public void infoTest() {
        // TODO: test info
    }

}
