/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestResultShortModel
 */
public class TestResultShortModelTest {
    private final TestResultShortModel model = new TestResultShortModel();

    /**
     * Model tests for TestResultShortModel
     */
    @Test
    public void testTestResultShortModel() {
        // TODO: test TestResultShortModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'outcome'
     */
    @Test
    public void outcomeTest() {
        // TODO: test outcome
    }

    /**
     * Test the property 'traces'
     */
    @Test
    public void tracesTest() {
        // TODO: test traces
    }

    /**
     * Test the property 'failureType'
     */
    @Test
    public void failureTypeTest() {
        // TODO: test failureType
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'testPoint'
     */
    @Test
    public void testPointTest() {
        // TODO: test testPoint
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'autoTest'
     */
    @Test
    public void autoTestTest() {
        // TODO: test autoTest
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

}
