/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestRunFillByConfigurationsPostModel
 */
public class TestRunFillByConfigurationsPostModelTest {
    private final TestRunFillByConfigurationsPostModel model = new TestRunFillByConfigurationsPostModel();

    /**
     * Model tests for TestRunFillByConfigurationsPostModel
     */
    @Test
    public void testTestRunFillByConfigurationsPostModel() {
        // TODO: test TestRunFillByConfigurationsPostModel
    }

    /**
     * Test the property 'testPointSelectors'
     */
    @Test
    public void testPointSelectorsTest() {
        // TODO: test testPointSelectors
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'testPlanId'
     */
    @Test
    public void testPlanIdTest() {
        // TODO: test testPlanId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'launchSource'
     */
    @Test
    public void launchSourceTest() {
        // TODO: test launchSource
    }

}
