/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestPointAnalyticResult
 */
public class TestPointAnalyticResultTest {
    private final TestPointAnalyticResult model = new TestPointAnalyticResult();

    /**
     * Model tests for TestPointAnalyticResult
     */
    @Test
    public void testTestPointAnalyticResult() {
        // TODO: test TestPointAnalyticResult
    }

    /**
     * Test the property 'countGroupByStatus'
     */
    @Test
    public void countGroupByStatusTest() {
        // TODO: test countGroupByStatus
    }

    /**
     * Test the property 'sumGroupByTester'
     */
    @Test
    public void sumGroupByTesterTest() {
        // TODO: test sumGroupByTester
    }

    /**
     * Test the property 'countGroupByTester'
     */
    @Test
    public void countGroupByTesterTest() {
        // TODO: test countGroupByTester
    }

    /**
     * Test the property 'countGroupByTestSuite'
     */
    @Test
    public void countGroupByTestSuiteTest() {
        // TODO: test countGroupByTestSuite
    }

    /**
     * Test the property 'countGroupByTesterAndStatus'
     */
    @Test
    public void countGroupByTesterAndStatusTest() {
        // TODO: test countGroupByTesterAndStatus
    }

}
