/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestResultStepCommentPutModel
 */
public class TestResultStepCommentPutModelTest {
    private final TestResultStepCommentPutModel model = new TestResultStepCommentPutModel();

    /**
     * Model tests for TestResultStepCommentPutModel
     */
    @Test
    public void testTestResultStepCommentPutModel() {
        // TODO: test TestResultStepCommentPutModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'text'
     */
    @Test
    public void textTest() {
        // TODO: test text
    }

    /**
     * Test the property 'stepId'
     */
    @Test
    public void stepIdTest() {
        // TODO: test stepId
    }

    /**
     * Test the property 'parentStepId'
     */
    @Test
    public void parentStepIdTest() {
        // TODO: test parentStepId
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

}
