/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestRunV2GetModel
 */
public class TestRunV2GetModelTest {
    private final TestRunV2GetModel model = new TestRunV2GetModel();

    /**
     * Model tests for TestRunV2GetModel
     */
    @Test
    public void testTestRunV2GetModel() {
        // TODO: test TestRunV2GetModel
    }

    /**
     * Test the property 'startedOn'
     */
    @Test
    public void startedOnTest() {
        // TODO: test startedOn
    }

    /**
     * Test the property 'completedOn'
     */
    @Test
    public void completedOnTest() {
        // TODO: test completedOn
    }

    /**
     * Test the property 'stateName'
     */
    @Test
    public void stateNameTest() {
        // TODO: test stateName
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'testPlanId'
     */
    @Test
    public void testPlanIdTest() {
        // TODO: test testPlanId
    }

    /**
     * Test the property 'testResults'
     */
    @Test
    public void testResultsTest() {
        // TODO: test testResults
    }

    /**
     * Test the property 'createdDate'
     */
    @Test
    public void createdDateTest() {
        // TODO: test createdDate
    }

    /**
     * Test the property 'modifiedDate'
     */
    @Test
    public void modifiedDateTest() {
        // TODO: test modifiedDate
    }

    /**
     * Test the property 'createdById'
     */
    @Test
    public void createdByIdTest() {
        // TODO: test createdById
    }

    /**
     * Test the property 'modifiedById'
     */
    @Test
    public void modifiedByIdTest() {
        // TODO: test modifiedById
    }

    /**
     * Test the property 'createdByUserName'
     */
    @Test
    public void createdByUserNameTest() {
        // TODO: test createdByUserName
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'launchSource'
     */
    @Test
    public void launchSourceTest() {
        // TODO: test launchSource
    }

}
