/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestSuiteChangeViewModel
 */
public class TestSuiteChangeViewModelTest {
    private final TestSuiteChangeViewModel model = new TestSuiteChangeViewModel();

    /**
     * Model tests for TestSuiteChangeViewModel
     */
    @Test
    public void testTestSuiteChangeViewModel() {
        // TODO: test TestSuiteChangeViewModel
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'configurations'
     */
    @Test
    public void configurationsTest() {
        // TODO: test configurations
    }

    /**
     * Test the property 'workItemCount'
     */
    @Test
    public void workItemCountTest() {
        // TODO: test workItemCount
    }

}
