/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestRunShortModel
 */
public class TestRunShortModelTest {
    private final TestRunShortModel model = new TestRunShortModel();

    /**
     * Model tests for TestRunShortModel
     */
    @Test
    public void testTestRunShortModel() {
        // TODO: test TestRunShortModel
    }

    /**
     * Test the property 'stateName'
     */
    @Test
    public void stateNameTest() {
        // TODO: test stateName
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'testPlanId'
     */
    @Test
    public void testPlanIdTest() {
        // TODO: test testPlanId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'isDeleted'
     */
    @Test
    public void isDeletedTest() {
        // TODO: test isDeleted
    }

}
