/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestPlanChangedFieldsViewModel
 */
public class TestPlanChangedFieldsViewModelTest {
    private final TestPlanChangedFieldsViewModel model = new TestPlanChangedFieldsViewModel();

    /**
     * Model tests for TestPlanChangedFieldsViewModel
     */
    @Test
    public void testTestPlanChangedFieldsViewModel() {
        // TODO: test TestPlanChangedFieldsViewModel
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'productName'
     */
    @Test
    public void productNameTest() {
        // TODO: test productName
    }

    /**
     * Test the property 'build'
     */
    @Test
    public void buildTest() {
        // TODO: test build
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'testSuite'
     */
    @Test
    public void testSuiteTest() {
        // TODO: test testSuite
    }

    /**
     * Test the property 'testPoints'
     */
    @Test
    public void testPointsTest() {
        // TODO: test testPoints
    }

    /**
     * Test the property 'testResults'
     */
    @Test
    public void testResultsTest() {
        // TODO: test testResults
    }

    /**
     * Test the property 'locking'
     */
    @Test
    public void lockingTest() {
        // TODO: test locking
    }

    /**
     * Test the property 'hasAutomaticDurationTimer'
     */
    @Test
    public void hasAutomaticDurationTimerTest() {
        // TODO: test hasAutomaticDurationTimer
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    public void attributesTest() {
        // TODO: test attributes
    }

}
