/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for TestPointResultModel
 */
public class TestPointResultModelTest {
    private final TestPointResultModel model = new TestPointResultModel();

    /**
     * Model tests for TestPointResultModel
     */
    @Test
    public void testTestPointResultModel() {
        // TODO: test TestPointResultModel
    }

    /**
     * Test the property 'testPointId'
     */
    @Test
    public void testPointIdTest() {
        // TODO: test testPointId
    }

    /**
     * Test the property 'aggregatedOutcome'
     */
    @Test
    public void aggregatedOutcomeTest() {
        // TODO: test aggregatedOutcome
    }

    /**
     * Test the property 'workItemGlobalId'
     */
    @Test
    public void workItemGlobalIdTest() {
        // TODO: test workItemGlobalId
    }

    /**
     * Test the property 'workItemName'
     */
    @Test
    public void workItemNameTest() {
        // TODO: test workItemName
    }

    /**
     * Test the property 'configurationName'
     */
    @Test
    public void configurationNameTest() {
        // TODO: test configurationName
    }

    /**
     * Test the property 'testResults'
     */
    @Test
    public void testResultsTest() {
        // TODO: test testResults
    }

    /**
     * Test the property 'attachments'
     */
    @Test
    public void attachmentsTest() {
        // TODO: test attachments
    }

}
