/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for WebHookPostModel
 */
public class WebHookPostModelTest {
    private final WebHookPostModel model = new WebHookPostModel();

    /**
     * Model tests for WebHookPostModel
     */
    @Test
    public void testWebHookPostModel() {
        // TODO: test WebHookPostModel
    }

    /**
     * Test the property 'projectId'
     */
    @Test
    public void projectIdTest() {
        // TODO: test projectId
    }

    /**
     * Test the property 'eventType'
     */
    @Test
    public void eventTypeTest() {
        // TODO: test eventType
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'requestType'
     */
    @Test
    public void requestTypeTest() {
        // TODO: test requestType
    }

    /**
     * Test the property 'shouldSendBody'
     */
    @Test
    public void shouldSendBodyTest() {
        // TODO: test shouldSendBody
    }

    /**
     * Test the property 'headers'
     */
    @Test
    public void headersTest() {
        // TODO: test headers
    }

    /**
     * Test the property 'queryParameters'
     */
    @Test
    public void queryParametersTest() {
        // TODO: test queryParameters
    }

    /**
     * Test the property 'isEnabled'
     */
    @Test
    public void isEnabledTest() {
        // TODO: test isEnabled
    }

    /**
     * Test the property 'shouldSendCustomBody'
     */
    @Test
    public void shouldSendCustomBodyTest() {
        // TODO: test shouldSendCustomBody
    }

    /**
     * Test the property 'customBody'
     */
    @Test
    public void customBodyTest() {
        // TODO: test customBody
    }

    /**
     * Test the property 'shouldReplaceParameters'
     */
    @Test
    public void shouldReplaceParametersTest() {
        // TODO: test shouldReplaceParameters
    }

    /**
     * Test the property 'shouldEscapeParameters'
     */
    @Test
    public void shouldEscapeParametersTest() {
        // TODO: test shouldEscapeParameters
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
