/*
 * API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.test_gear.client.model;

import org.junit.jupiter.api.Test;

/**
 * Model tests for WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel
 */
public class WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModelTest {
    private final WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel model = new WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel();

    /**
     * Model tests for WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel
     */
    @Test
    public void testWorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel() {
        // TODO: test WorkItemLinkChangeViewModelArrayWorkItemChangedFieldViewModel
    }

    /**
     * Test the property 'oldValue'
     */
    @Test
    public void oldValueTest() {
        // TODO: test oldValue
    }

    /**
     * Test the property 'newValue'
     */
    @Test
    public void newValueTest() {
        // TODO: test newValue
    }

}
